name = "test"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["test"]

[[depends-on]]
gnat_arm_elf = "^14"
gnatprove = "^14"
rp2350 = "*"

[[pins]]
rp2350 = { path='..' }

[[actions]]
type = "post-build"
command = ["gnatprove", "--mode=all", "--warnings=off", "--output-header"]

[build-profiles]
"*" = "validation"
