name = "test"
description = ""
version = "0.1.0-dev"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

executables = ["test"]

[[depends-on]]
gnat_arm_elf = "^14.2.1"
rp2350 = "*"
gnatprove = "^14.1.1"

[[pins]]
rp2350 = { path='..' }

[build-switches]
release.optimization = ["-Os", "-gnatn2", "-gnatp"]

[[actions]]
type = "post-build"
command = ["gnatprove", "--mode=all", "--warnings=off", "--output-header"]

[build-profiles]
"*" = "development"
